PizzaShop/Models/Catalog/Option.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PizzaShop.Models.Catalog
{   
    public class Option
    {
        #region Properties

        public int OptionId { get; set; }

        [Required(ErrorMessage="Name is required")]
        public string Name { get; set; }

        public virtual List<OptionValue> Values { get; set; }

        #endregion

        #region Constructor

        public Option()
        {
            Values = new List<OptionValue>();
        }

        #endregion

    }
}

PizzaShop/Areas/Admin/Controllers/OptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaShop.Models;
using PizzaShop.Models.Catalog;
using System.Web.Helpers;
using System.IO;
using PizzaShop.Models.Repositories;

namespace PizzaShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Employee")]
    public class OptionsController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Admin/Options/
        public ActionResult Index()
        {
            var options = unitOfWork.optionRepository.GetAll().ToList();
            return View(options);
        }

        //
        // GET: /Admin/Options/Detail/4
        public ActionResult Detail(int id)
        {
            Option option = unitOfWork.optionRepository.Get(id);
            if (option == null)
            {
                return View("NotFound");
            }
            return View(option);
        }

        //
        // GET: /Admin/Options/Edit/4
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Option option = unitOfWork.optionRepository.Get(id);
            if (option == null)
            {
                return View("NotFound");
            }
            return View(option);
        }

        //
        // POST: /Admin/Options/Edit/4
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(Option option, IEnumerable<HttpPostedFileBase> file)
        {
            if (ModelState.IsValid)
            {
                int i = 0;
                if (file != null)
                {
                    foreach (var _file in file)
                    {
                        if (_file != null && _file.ContentLength > 0)
                        {
                            if (!option.Values[i].Image.Equals("~/Uploads/Default.jpg"))
                            {
                                System.IO.File.Delete(Server.MapPath(option.Values[i].Image));
                            }
                            string image = "~/Uploads/option-" + option.Values[i].Name + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(_file.FileName);
                            string filePath = Server.MapPath(image);
                            _file.SaveAs(filePath);
                            option.Values[i].Image = image;
                        }
                        i++;
                    }
                }
                unitOfWork.optionRepository.Update(option);
                unitOfWork.Save();
                return RedirectToAction("Detail", new { id = option.OptionId });
            }
            return View(option);
        }

        //
        // GET: Admin/Options/New
        [Authorize(Roles = "Administrator")]
        public ActionResult New()
        {
            Option option = new Option();
            return View(option);
        }

        //
        // POST: Admin/Options/New/4
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult New(FormCollection formValues)
        {
            Option option = new Option();
            if (TryUpdateModel(option))
            {
                unitOfWork.optionRepository.Add(option);
                unitOfWork.Save();
                return RedirectToAction("Edit", new { id = option.OptionId });
            }
            return View(option);
        }

        //
        // GET: Admin/Options/Delete
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            Option option = unitOfWork.optionRepository.Get(id);
            if (option == null)
            {
                return View("NotFound");
            }
            return View(option);
        }

        //
        // POST: Admin/Options/Delete/4

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, string confirmButton)
        {
            Option option = unitOfWork.optionRepository.Get(id);
            foreach (OptionValue ov in option.Values)
            {
                if (!ov.Image.Equals("~/Uploads/Default.jpg"))
                {
                    System.IO.File.Delete(Server.MapPath(ov.Image));
                }
            }
            var productOptions = unitOfWork.productRepository.GetProductOptions().Where(o => o.OptionId == option.OptionId);
            foreach (var po in productOptions)
            {
                unitOfWork.productRepository.DeleteProductOption(po);
            }
            unitOfWork.Save();
            unitOfWork.optionRepository.Delete(option);
            unitOfWork.Save();
            return View("Deleted");
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddValue(int id)
        {
            OptionValue ov = new OptionValue();
            ov.OptionId = id;
            return View(ov);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult AddValue(int id, FormCollection formValues, HttpPostedFileBase file)
        {
            

            OptionValue ov = new OptionValue();
            if (TryUpdateModel(ov))
            {
                //TODO
                if (file != null && file.ContentLength > 0)
                {
                    string image = "~/Uploads/option" + ov.Name + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(file.FileName);
                    string filePath = Server.MapPath(image);
                    file.SaveAs(filePath);
                    ov.Image = image;
                }
                else
                {
                    ov.Image = "~/Uploads/Default.jpg";
                }
                
                unitOfWork.optionRepository.Get(id).Values.Add(ov);
                unitOfWork.Save();

                return RedirectToAction("Edit", new { id = ov.OptionId });
            }
            return View(ov);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteOptionValue(int id)
        {
            OptionValue ov = unitOfWork.optionRepository.GetOptionValue(id);
            if (!ov.Image.Equals("~/Uploads/Default.jpg"))
            {
                System.IO.File.Delete(Server.MapPath(ov.Image));
            }

            //Delete All Product Option Values associated with deleted option
            var productOptionValues = unitOfWork.productRepository.GetProductOptionValues().Where(pov => pov.OptionValueId == id);
            foreach (var pov in productOptionValues)
            {
                unitOfWork.productRepository.DeleteProductOptionValue(pov);
            }
            unitOfWork.Save();
            unitOfWork.optionRepository.DeleteOptionValue(ov);
            unitOfWork.Save();
            return RedirectToAction("Edit", new { id = ov.OptionId });
        }



    }
}

PizzaShop/Areas/Admin/Views/Options/AddValue.cshtml
@model PizzaShop.Models.Catalog.OptionValue

@{
    ViewBag.Title = "AddValue";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>AddValue</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("AddValue", "Options", 
                    FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>OptionValue</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div>
        <label for="file">Image</label>
        <input type="file" name="file" id="file" />
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PizzaShop/Areas/Admin/Views/Options/Delete.cshtml
@model PizzaShop.Models.Catalog.Option

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete Option</h2>

<h3>Are you sure you want to delete this?</h3>
<p><b>This may cause deletion of all Product options associated with this option!!!</b></p>
<fieldset>
    <legend>Option</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <legend>Values</legend>
    <table>
    @for (int i =0; i<Model.Values.Count(); i++)
    {
    <tr>
        <td>
        @Html.DisplayFor(model => Model.Values[i].Name)
        </td>
        <td>
        <img src="@Url.Content(Model.Values[i].Image)", title=@Model.Values[i].Name, alt="Option Value", height=50, width=50 />
        </td>

    </tr>
    }
    </table>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PizzaShop/Areas/Admin/Views/Options/Deleted.cshtml
@{
    ViewBag.Title = "Deleted";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Option deleted</h2>
<div>
    <p>Option was succesfully deleted.</p>
</div>
<div>
    <p>@Html.ActionLink("Back to List","Index")</p>
</div>

PizzaShop/Areas/Admin/Views/Options/Detail.cshtml
@model PizzaShop.Models.Catalog.Option

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Detail</h2>

<fieldset>
    <legend>Option</legend>
    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <legend>Values</legend>
    <table>
    @for (int i =0; i<Model.Values.Count(); i++)
    {
    <tr>
        <td>
        @Html.DisplayFor(model => Model.Values[i].Name)
        </td>
        <td>
        <img src="@Url.Content(Model.Values[i].Image)", title=@Model.Values[i].Name, alt="Option Value", height=50, width=50 />
        </td>

    </tr>
    }
    </table>
</fieldset>
<p>
    @if(User.IsInRole("Administrator"))
    {
    @Html.ActionLink("Edit", "Edit", new { id=Model.OptionId }) <text> | </text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

PizzaShop/Areas/Admin/Views/Options/Edit.cshtml
@model PizzaShop.Models.Catalog.Option

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "Options", 
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Option</legend>

        @Html.HiddenFor(model => model.OptionId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <legend>Values</legend>
        
        @Html.EditorFor(model => model.Values)

        <div>@Html.ActionLink("Add Value", "AddValue", new { id = Model.OptionId })</div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PizzaShop/Areas/Admin/Views/Options/Index.cshtml
@model IEnumerable<PizzaShop.Models.Catalog.Option>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Options</h2>

<p>
    @if (User.IsInRole("Administrator"))
    {
    @Html.ActionLink("Create New", "New")
    }
</p>
<table>
    <tr>
        <th>
            ID
        </th>
        <th>
            Name
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OptionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Details", "Detail", new { id=item.OptionId })
            
            @if (User.IsInRole("Administrator"))
            {
                <text> | </text>
                @Html.ActionLink("Edit", "Edit", new { id = item.OptionId }) <text> | </text>
                @Html.ActionLink("Delete", "Delete", new { id = item.OptionId })
            }
        </td>
    </tr>
}

</table>

PizzaShop/Areas/Admin/Views/Options/New.cshtml
@model PizzaShop.Models.Catalog.Option

@{
    ViewBag.Title = "New";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>New</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Option</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PizzaShop/Areas/Admin/Views/Options/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>NotFound</h2>
Sorry! Your item no longer exist.