PizzaShop/Models/Catalog/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PizzaShop.Models.Catalog
{
    public class Category
    {
        #region Properties
        public int CategoryId { get; set; }

        [Required(ErrorMessage="Name is required.")]
        [StringLength(30, ErrorMessage="Name may not be longer than 30 characters")]
        public string Name { get; set; }

        public int CategoryImageId { get; set; }
        public virtual CategoryImage Image { get; set; }
        #endregion
    }
}

PizzaShop/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaShop.Models;
using PizzaShop.Models.Catalog;
using PizzaShop.Models.Repositories;
using System.IO;

namespace PizzaShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Employee")]
    public class CategoriesController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();
        //
        // GET: /Admin/Categories/

        public ActionResult Index()
        {
            var categories = unitOfWork.categoryRepository.GetAll();
            return View(categories);
        }


        //
        // GET: /Admin/Categories/Detail/4
        public ActionResult Detail(int id)
        {
            Category category = unitOfWork.categoryRepository.Get(id);
            if (category == null)
                return View("NotFound");
            else
                return View(category);
        }


        //
        // GET /Admin/Categories/Edit/4
        [Authorize(Roles="Administrator")]
        public ActionResult Edit(int id)
        {
            Category category = unitOfWork.categoryRepository.Get(id);
            if (category == null)
                return View("NotFound");
            else
            return View(category);
        }


        //
        // POST /Admin/Categories/Edit/4
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id, FormCollection formValues, HttpPostedFileBase file)
        {
            //TODO Obraykz
            Category category = unitOfWork.categoryRepository.Get(id);
            if (TryUpdateModel(category))
            {
                if (file != null && file.ContentLength > 0)
                {
                    if (!category.Image.Url.Equals("~/Uploads/Default.jpg"))
                    {
                        System.IO.File.Delete(Server.MapPath(category.Image.Url));
                    }
                    string image = "~/Uploads/category-" + category.Name + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(file.FileName);
                    string filePath = Server.MapPath(image);
                    file.SaveAs(filePath);
                    category.Image.Url = image;
                }
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }


        //
        // GET /Admin/Categories/New
        [Authorize(Roles = "Administrator")]
        public ActionResult New()
        {
            Category category = new Category();
            return View(category);
        }


        //
        // POST /Admin/Categories/New
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult New(FormCollection formValues, HttpPostedFileBase file)
        {
            Category category = new Category();
            category.Image = new CategoryImage();
            if (TryUpdateModel(category))
            {
                if (unitOfWork.categoryRepository.GetAll().Where(c => c.Name.Equals(category.Name)).Count() > 0)
                {
                    ModelState.AddModelError(string.Empty, "Category whith name: " + category.Name + " already exist. Change Name.");
                    return View(category);
                }
                if (file != null && file.ContentLength > 0)
                {
                    string image = "~/Uploads/category-" + category.Name + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(file.FileName);
                    string filePath = Server.MapPath(image);
                    file.SaveAs(filePath);
                    category.Image.Url = image;
                }
                else
                {
                    category.Image.Url = "~/Uploads/Default.jpg";
                }
                unitOfWork.categoryRepository.Add(category);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }


        //
        //GET /Admin/Categories/Delete/4
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            Category category = unitOfWork.categoryRepository.Get(id);
            int products = unitOfWork.productRepository.GetAll().Where(p => p.CategoryId == id).Count();
            ViewBag.products = products;
            if (category == null)
                return View("NotFound");
            else
            return View(category);
        }


        //
        // POST /Admin/Categories/Delete/4
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, string confirmButton)
        {
            Category category = unitOfWork.categoryRepository.Get(id);
            if (!category.Image.Url.Equals("~/Uploads/Default.jpg"))
            {
                System.IO.File.Delete(Server.MapPath(category.Image.Url));
            }
            if (category == null)
                return View("NotFound");

            unitOfWork.categoryRepository.Delete(category);
            unitOfWork.Save();

            return View("Deleted");
        }
    }
}

PizzaShop/Areas/Admin/Views/Categories/Delete.cshtml
@model PizzaShop.Models.Catalog.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete category</h2>

<h3>Are you sure you want to delete this?</h3>
<em>Delete this category causes the deletion of all products in category!!!</em>
Number of affected products: @ViewBag.products
<fieldset>
    <legend>Category</legend>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Image</div>
    <div class="display-field">
        <img src="@Url.Content(Model.Image.Url)" title="@Model.Name" width="50" height="50" />
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PizzaShop/Areas/Admin/Views/Categories/Deleted.cshtml
@{
    ViewBag.Title = "Deleted";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Category deleted</h2>
<div>
    <p>Category was succesfully deleted.</p>
</div>
<div>
    <p>@Html.ActionLink("Back to List","Index")</p>
</div>

PizzaShop/Areas/Admin/Views/Categories/Detail.cshtml
@model PizzaShop.Models.Catalog.Category

@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Detail</h2>

<fieldset>
    <legend>Category</legend>

    <div class="display-label">ID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CategoryId)
    </div>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Image</div>
    <div class="display-field">
        <img src="@Url.Content(Model.Image.Url)" title="@Model.Name" width="50" height="50" />
    </div>

    
</fieldset>
<p>
    @if(User.IsInRole("Administrator"))
    {
        @Html.ActionLink("Edit", "Edit", new { id=Model.CategoryId }) <text> | </text>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

PizzaShop/Areas/Admin/Views/Categories/Edit.cshtml
@model PizzaShop.Models.Catalog.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit category</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Edit", "Categories",
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Category</legend>

        @Html.HiddenFor(model => model.CategoryId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            <H3>Image</H3>
        </div>
        <div class="editor-field">
            <img src="@Url.Content(Model.Image.Url)" title="@Model.Name" width="50" height="50" />
            <input type="file" name="file" />
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PizzaShop/Areas/Admin/Views/Categories/Index.cshtml
@model IEnumerable<PizzaShop.Models.Catalog.Category>

@{
    ViewBag.Title = "Categories";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Categories</h2>

<p>
    @if (User.IsInRole("Administrator"))
    {
    @Html.ActionLink("Add new category", "New")
    }
</p>
<table>
    <tr>
        <th>
            Image
        </th>
        <th>
            ID
        </th>
        <th>
            Name
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img src="@Url.Content(item.Image.Url)" title="@item.Name" width="50" height="50" />
        </td>
        <td>
           @Html.DisplayFor(modelItem =>item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Details", "Detail", new { id=item.CategoryId }) 
            @if (User.IsInRole("Administrator"))
            {
                <text> | </text>@Html.ActionLink("Edit", "Edit", new { id=item.CategoryId }) <text>|</text>
                @Html.ActionLink("Delete", "Delete", new { id=item.CategoryId })
            }
        </td>
    </tr>
}

</table>

PizzaShop/Areas/Admin/Views/Categories/New.cshtml
@model PizzaShop.Models.Catalog.Category

@{
    ViewBag.Title = "New";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>New</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("New", "Categories",
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Category</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            Image
        </div>
        <input type="file" name="file" />

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PizzaShop/Areas/Admin/Views/Categories/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>NotFound</h2>
Sorry! Your item no longer exist.