PizzaShop/Models/Catalog/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PizzaShop.Models.Catalog
{
    public class Cart
    {
        public List<CartItem> Items { get; private set; }

        public static readonly Cart Instance;

        public double Total
        {
            get
            {
                double _total = 0;
                foreach (var item in Items)
                {
                    _total += item.Total;
                }
                return _total;
            }
        }

        static Cart()
        {
            if (HttpContext.Current.Session["Cart"] == null)
            {
                Instance = new Cart();
                Instance.Items = new List<CartItem>();
                HttpContext.Current.Session["Cart"] = Instance;
            }
            else
            {
                Instance = (Cart)HttpContext.Current.Session["Cart"];
            }
        }

        protected Cart() { }

        public CartItem GetItem(int index)
        {
            return Items.ElementAt(index);
        }

        public void UpdateItem(int index, CartItem item)
        {
            Items.RemoveAt(index);
            Items.Add(item);
        }

        public void AddItem(Product product)
        {

            CartItem newItem = new CartItem();
            newItem.Options = new List<CartItemOptionValue>();
            newItem.Product = product;
            foreach (var option in product.Options)
            {
                CartItemOptionValue cartItemValue = new CartItemOptionValue();
                cartItemValue.Option = option;
                cartItemValue.Value = option.Values.FirstOrDefault(v => v.Default==true);
                newItem.Options.Add(cartItemValue);
            }
            Items.Add(newItem);
        }

        public void AddItem(Product product, IEnumerable<ProductOptionValue> options, string comment)
        {
            CartItem newItem = new CartItem();
            newItem.Options = new List<CartItemOptionValue>();
            newItem.Product = product;
            newItem.Comment = comment;
            foreach (var option in options)
            {
                CartItemOptionValue cartItemValue = new CartItemOptionValue();
                cartItemValue.Option = option.ProductOption;
                cartItemValue.Value = option;
                newItem.Options.Add(cartItemValue);
            }
            Items.Add(newItem);
        }

        public void RemoveItem(int id)
        {
            Items.RemoveAt(id);
        }

        public void ClearCart()
        {
            Items.Clear();
        }

        public Order CreateOrder(Order order)
        {
            foreach (var item in Items)
            {
                var orderItem = new OrderItem();

                orderItem.Name = item.Product.Name;
                orderItem.Price = item.Product.Price;
                orderItem.Total = item.Total;
                orderItem.Wish = item.Comment;
                orderItem.ArchivedProductId = item.Product.ProductId;
                foreach (var option in item.Options)
                {
                    var value = new OrderItemOptionValue();
                    value.Name = option.Option.Name;
                    value.Value = option.Value.Name;
                    value.Price = option.Value.Price;
                    value.ArchivedProductOptionId = option.Option.ProductOptionId;
                    value.ArchivedProductOptionValueId = option.Value.ProductOptionValueId;

                    orderItem.Options.Add(value);
                }
                order.Items.Add(orderItem);

            }
            order.Total = this.Total;
            order.DateAdded = DateTime.Now;
            return order;
        }
    }
}

PizzaShop/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaShop.Models.Repositories;
using PizzaShop.Models;

namespace PizzaShop.Controllers
{
    [Authorize(Roles="Customer")]
    public class ProfilesController : BaseController
    {

        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Profiles/

        public ActionResult Index()
        {
            var orders = db.orderRepository.GetAll().Where(o => o.User.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase));
            var profile = db.profileRepository.Get(User.Identity.Name);
            ViewBag.profile = profile;
            return View(orders);
        }

        public ActionResult OrderDetail(int id)
        {
            var order = db.orderRepository.Get(id);
            if (order != null)
            {
                if (order.User.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase))
                {
                    return View(order);
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult CreateProfile()
        {
            Profile profile = new Profile();
            return View(profile);
        }

        [HttpPost]
        public ActionResult CreateProfile(FormCollection fromValues)
        {
            var profile = new Profile();
            if (TryUpdateModel(profile))
            {
                profile.Owner = User.Identity.Name;
                unitOfWork.profileRepository.Add(profile);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(profile);
        }

        public ActionResult EditProfile()
        {
            var profile = unitOfWork.profileRepository.Get(User.Identity.Name);

            return View(profile);
        }

        [HttpPost]
        public ActionResult EditProfile(FormCollection formValues)
        {
            var profile = unitOfWork.profileRepository.Get(User.Identity.Name);
            if (TryUpdateModel(profile))
            {
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(profile);
            }



    }
}

PizzaShop/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaShop.Models.Catalog;
using PizzaShop.Models;
using System.Web.Security;

namespace PizzaShop.Controllers
{
    public class ShopController : BaseController
    {
        //
        // GET: /Shop/


        public ActionResult Products(string category)
        {
            if (!String.IsNullOrEmpty(category))
            {
                var products = db.productRepository.GetAll(category);
                ViewBag.CategoryName = category;
                return View(products);
            }
            else 
            {
                var products = db.productRepository.GetAll();
                if (products == null) { System.Diagnostics.Debug.WriteLine("ni4"); };
                ViewBag.CategoryName = "All";
                return View(products); 
            }
        }

        public ActionResult AddToCart(int id)
        {
            Product product = db.productRepository.Get(id);
            return View(product);
        }

        [HttpPost]
        public ActionResult AddToCart(int id, FormCollection form)
        {
            Product product = db.productRepository.Get(id);
            string comment = form["Comment"];
            List<ProductOptionValue> options = new List<ProductOptionValue>();
            foreach (var option in product.Options)
            {
                options.Add(option.Values.FirstOrDefault(v => v.ProductOptionValueId == Convert.ToInt32(form[option.Name])));
            }
            Cart1.My().AddItem(product, options, comment);
            //Cart.Instance.AddItem(product, options, comment);
            return RedirectToAction("Products",new {category=product.Category.Name});
        }

        public ActionResult RemoveFromCart(int id)
        {
            Cart1.My().RemoveItem(id);

            //Cart.Instance.RemoveItem(id);
            return RedirectToAction("Products");
        }

        //
        // GET: /Shop/Checkout
        [Authorize(Roles="Customer,Vendor,Administrator")]
        public ActionResult Checkout()
        {
            Order order = new Order();
            Profile profile = db.profileRepository.Get(User.Identity.Name);
            if (profile != null)
            {
                order.Adress = profile.Address;
                order.FirstName = profile.FirstName;
                order.LastName = profile.LastName;
            }
            order.User = User.Identity.Name;
            order.Mail = Membership.GetUser().Email;
            
            return View(order);
        }

        //
        // POST /Shop/Checkout
        [HttpPost]
        [Authorize(Roles = "Customer,Vendor,Administrator")]
        public ActionResult Checkout(FormCollection formValues)
        {
            Order order = new Order();
            //Prevent against reload page and resend order to system
            if (/*PizzaShop.Models.Catalog.Cart.Instance.Items.Count() == 0*/Cart1.My().Items.Count()==0)
            {
                return RedirectToAction("Products");
            }
            if(TryUpdateModel(order)) 
            {
                Order NewOrder = Cart1.My().CreateOrder(order);
                Cart1.My().ClearCart();
                //PizzaShop.Models.Catalog.Cart.Instance.ClearCart();
                var status = db.orderRepository.GetOrderStatuses().FirstOrDefault(os => os.Name.Equals("Pending"));
                NewOrder.OrderStatusId = status.OrderStatusId;
                NewOrder.User = User.Identity.Name;
                //cost
                foreach (var item in NewOrder.Items)
                {
                    var product_cost = db.productRepository.Get(item.ArchivedProductId).Costs;
                    item.Costs = product_cost;
                }
                db.orderRepository.Add(NewOrder);
                db.Save();
                return View("Accepted",NewOrder.OrderId);
            }
                return View(order);
        }
    }
}

PizzaShop/Views/Shared/Cart.cshtml
@model PizzaShop.Models.Catalog.ShoppingCart
@if (Model.Items.Count > 0)
{
<table>
    <tr>
        <th>
            Product
        </th>
        <th>
            Možnosti
        </th>
        <th>
            Špeciálne prianie
        </th>
        <th>
            Cena
        </th>
        <th></th>
    </tr>
@{int i = 0;}
@foreach (var item in Model.Items)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            <ul>
            @foreach (var option in item.Options)
            {
                <li>@option.Option.Name: -@option.Value.Name</li>
            }
            </ul>
        </td>
        <td>
            @Html.DisplayFor(modeItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.ActionLink("Odstráň", "RemoveFromCart","Shop", new { id = i },null)
        </td>
    </tr>
       i++;
}

</table>
<div>
    Suma: @Model.Total
</div>
}
else
{
    <div>
        Košík je prázdny
    </div>
}

PizzaShop/Views/Shared/CartDetail.cshtml
@model PizzaShop.Models.Catalog.ShoppingCart
@if (Model.Items.Count > 0)
{
<table>
    <tr>
        <th>
            Product
        </th>
        <th>
            Možnosti
        </th>
        <th>
            Špeciálne prianie
        </th>
        <th>
            Cena
        </th>
    </tr>
@{int i = 0;}
@foreach (var item in Model.Items)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            <ul>
            @foreach (var option in item.Options)
            {
                <li>@option.Option.Name: -@option.Value.Name</li>
            }
            </ul>
        </td>
        <td>
            @Html.DisplayFor(modeItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
    </tr>
       i++;
}

</table>
<div>
    Suma: @Model.Total
</div>
}
else
{
    <div>
        Košík je prázdny    
    </div>
}

PizzaShop/Views/Shared/_Cart.cshtml
@model PizzaShop.Models.Catalog.ShoppingCart
           
@if (Model.Items.Count() > 0)
{
    <text>Items in Cart: <strong>@Model.Items.Count()</strong></text>
    <text>Price: <strong>@Model.Total</strong></text> <br />
    @Html.ActionLink("-", "Checkout", "Shop", null, new { @class = "checkout" })
}
else
{
    <text>Váš košík je prázdny</text>
}

PizzaShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
                <div id="minicart">
               @Html.Partial("_Cart",/*PizzaShop.Models.Catalog.Cart.Instance*/(PizzaShop.Models.Catalog.ShoppingCart)ViewBag.cart)
                </div>
            <div id="title">            
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">

                    
                    @foreach (var c in ViewBag.Categories as List<PizzaShop.Models.Catalog.Category>)
                    {
                        <li>@Html.ActionLink(c.Name, "Products", "Shop", new {category = c.Name }, null)</li>
                    }

                    |
                    <li>@Html.ActionLink("Domov", "Index", "Home")</li>
                    <li>@Html.ActionLink("O Nás", "About", "Home")</li>
                    @if (User.IsInRole("Employee"))
                    {
                    <li>@Html.ActionLink("Admin", "Index", "Admin/Statistics")</li>
                    }
                     @if (User.IsInRole("Customer"))
                    {
                    <li>@Html.ActionLink("Môj Profil", "Index", "Profiles")</li>
                    }
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
            @ViewBag.test
        </section>
        <footer>
        @Html.Partial("Cart",/*PizzaShop.Models.Catalog.Cart.Instance*/(PizzaShop.Models.Catalog.ShoppingCart)ViewBag.cart)
        </footer>
    </div>
</body>
</html>

PizzaShop/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Vitajte <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ] <br />
    </text>
}
else {
    @:[ @Html.ActionLink("Log In", "LogOn", "Account") ]
}